syntax = "proto3";

package chat.v1;

import "common/v1/common.proto";
import "google/protobuf/timestamp.proto";
import "resource/v1/resource.proto";

// The chat service provides methods for sending messages.
service ChatService {
  // Creates a new channel.
  //
  // Requires Authentication: Only authorized users can create channels.
  rpc CreateChannel(CreateChannelRequest) returns (CreateChannelResponse);

  // Delete a channel.
  //
  // Requires Authentication: Only authorized users can delete channels.
  rpc DeleteChannel(DeleteChannelRequest) returns (DeleteChannelResponse);

  // Sets the user channel permission.
  //
  // Requires Authentication: Only authorized users can set user permissions.
  rpc SetUserPerm(SetUserPermRequest)
      returns (SetUserPermResponse);

  // Invite a user to a channel.
  //
  // Requires Authentication: Only authorized users can invite users.
  rpc Invite(InviteRequest) returns (InviteResponse);

  // Reads messages from a channel.
  //
  // Requires Authentication: Only authorized & invited users can read messages.
  rpc Read(ReadRequest) returns (ReadResponse);

  // Sends a message to a channel.
  //
  // Requires Authentication: Only authorized users can send messages.
  rpc Send(SendRequest) returns (SendResponse);

  // Deletes a message.
  //
  // Requires Authentication: Only authorized users can delete messages.
  rpc DeleteMessage(DeleteMessageRequest) returns (DeleteMessageResponse);
}

// The request message for creating a channel.
message CreateChannelRequest {
  // The name of the channel.
  string name = 2;
  // The description of the channel.
  string description = 3;
  // The members of the channel.
  map<string, ChannelPermission> members = 4;
}

// The response message for creating a channel.
message CreateChannelResponse {
  // The result of the create operation.
  oneof result {
    // The channel that was created.
    Channel channel = 1;
    // The error, if any.
    common.v1.Error error = 2;
  }
}

// The request message for deleting a channel.
message DeleteChannelRequest {
  // The ID of the channel to delete.
  fixed64 channel_id = 1;
}

// The response message for deleting a channel.
message DeleteChannelResponse {
  // The error, if any.
  optional common.v1.Error error = 1;
}

// The request message for setting a user's permission in a channel.
message SetUserPermRequest {
  // The target User ID.
  string user_id = 1;
  // The ID of the channel to set the permission for.
  fixed64 channel_id = 2;
  // The permission to set.
  ChannelPermission permission = 3;
}

// The response message for setting a user's permission in a channel.
message SetUserPermResponse {
  // The error, if any.
  optional common.v1.Error error = 1;
}

// The request message for inviting a user to a channel.
message InviteRequest {
  // The ID of the channel to invite to.
  fixed64 channel_id = 1;
  // The ID of the user to invite.
  string user_id = 2;
  // Whether to uninvite the user.
  bool uninvite = 3;
}

// The response message for inviting a user to a channel.
message InviteResponse {
  // The error, if any.
  optional common.v1.Error error = 1;
}

// The request message for reading messages.
message ReadRequest {
  // The ID of the channel to read messages from.
  fixed64 channel_id = 1;
  // The maximum number of messages to load.
  uint32 limit = 2;
  // The timestamp to start reading from.
  google.protobuf.Timestamp start_time = 3;
}

message ReadResponse {
  // The messages read from the channel.
  repeated Message messages = 1;
  // The error, if any.
  optional common.v1.Error error = 2;
}

// The request message for sending a message.
message SendRequest {
  // The ID of the channel to send the message to.
  fixed64 channel_id = 1;
  // The message content.
  resource.v1.Content content = 2;
}

// The response message for sending a message.
message SendResponse {
  // The result of the send operation.
  oneof result {
    // The created message.
    Message message = 1;
    // The error, if any.
    common.v1.Error error = 2;
  }
}

// The request message for deleting a message.
message DeleteMessageRequest {
  // The ID of the message to delete.
  fixed64 message_id = 1;
}

// The response message for deleting a message.
message DeleteMessageResponse {
  // The error, if any.
  optional common.v1.Error error = 1;
}

// A messaging channel.
//
// Can be a private channel to a user or a public channel.
message Channel {
  // The ID of the channel.
  fixed64 channel_id = 1;
  // The name of the channel.
  string name = 2;
  // The description of the channel.
  string description = 3;
  // The members of the channel.
  map<string, ChannelPermission> members = 4;
}

enum ChannelPermission {
  // The user has read-only access.
  CHANNEL_PERMISSION_READ_ONLY_UNSPECIFIED = 0;
  // The user has read and write access.
  CHANNEL_PERMISSION_READ_WRITE = 1;
  // The user has elevated privileges over the channel and members.
  CHANNEL_PERMISSION_MANAGER = 2;
}

// A concrete post sent to a channel.
message Message {
  // The ID of the message.
  fixed64 message_id = 1;
  // The ID of the channel the message was sent to.
  fixed64 channel_id = 2;
  // The ID of the user who sent the message.
  string user_id = 3;
  // The timestamp when the message was created.
  google.protobuf.Timestamp created_at = 4;
  // The content of the message.
  resource.v1.Content content = 5;
}
