syntax = "proto3";

import "google/protobuf/duration.proto";

package common.v1;

// A JWT token claim.
message Auth {
  // The user ID.
  string user_id = 1;
  // The expiration date as a Unix timestamp.
  uint64 exp = 2;
}

// Message represents an error that occurred during a request.
message Error {
  // The error message.
  string message = 1;
  // The internal error type.
  oneof type {
    // An internal error occurred.
    InternalError internal = 2;
    // The client is not authorized to perform this action.
    //
    // Unlike `RestrictedError`, this error is caused by authentication failure.
    UnauthorizedError unauthorized = 3;
    // The requested item was not found.
    NotFoundError not_found = 4;
    // The requested item already exists.
    AlreadyExistsError already_exists = 5;
    // The request format was invalid.
    InvalidFormatError invalid_format = 6;
    // The user is not permitted to perform this action.
    //
    // Unlike `UnauthorizedError`, this error is caused by policy violation or permission restrictions.
    RestrictedError restricted = 7;
    // The requested resource is unwanted by the user.
    UnwantedError unwanted = 8;
    // The client got rate limited.
    RateLimitError rate_limit = 9;
  }
}

// An internal error occurred.
message InternalError {
}

// The client is not authorized to perform this action.
//
// Unlike `RestrictedError`, this error is caused by authentication failure.
message UnauthorizedError {
}

// The requested item was not found.
message NotFoundError {
}

// The requested item already exists.
message AlreadyExistsError {
}

// The request format was invalid.
message InvalidFormatError {
}

// The user is not permitted to perform this action.
//
// Unlike `UnauthorizedError`, this error is caused by policy violation or permission restrictions.
message RestrictedError {
}

// The requested resource is unwanted by the user.
message UnwantedError {
}

// The client got rate limited.
message RateLimitError {
  // The duration to wait before retrying.
  google.protobuf.Duration try_again_in = 1;
}
