syntax = "proto3";

package general.v1;
import "user/v1/user.proto";

// Service for general server mechanics.
service GeneralService {
  // Get the server configuration.
  rpc Config(ConfigRequest) returns (ConfigResponse);

  // Clear the server state for a new test.
  //
  // Only available in testing mode.
  rpc ClearState(ClearStateRequest) returns (ClearStateResponse);

  // Get an email verification token.
  //
  // Only available in testing mode.
  rpc EmailToken(EmailTokenRequest) returns (EmailTokenResponse);

  // Get a list of available services.
  //
  // Only available in testing mode.
  rpc Services(ServicesRequest) returns (ServicesResponse);

  rpc TestUsers(TestUsersRequest) returns (TestUsersResponse);
}

// A request to get the server configuration.
message ConfigRequest {
}

// A response from a request to get the server configuration.
message ConfigResponse {
  // The server API version.
  string version = 1;
  // The chunk size to use for resource operations.
  uint32 resource_chunk_size = 2;
}

// A request to clear the server state.
//
// Only available in testing mode.
message ClearStateRequest {
}

// A response from a request to clear the server state.
//
// Only available in testing mode.
message ClearStateResponse {
}

// A request to get an email verification token.
//
// Only available in testing mode.
message EmailTokenRequest {
  // The email address to get a token for.
  string email = 1;
}

// A response from a request to get an email verification token.
//
// Only available in testing mode.
message EmailTokenResponse {
  // The email verification token.
  string token = 1;
}

// A request to get a list of available services.
//
// Only available in testing mode.
message ServicesRequest {
}

// A response from a request to get a list of available services.
//
// Only available in testing mode.
message ServicesResponse {
  // A list of available services.
  repeated ServiceDescriptor services = 1;
}

// A request for getting test user data.
//
// Only available in testing mode.
message TestUsersRequest {
}

// A response for getting test user data.
//
// Only available in testing mode.
message TestUsersResponse {
  // A normal test user.
  user.v1.User user = 1;
  // A moderator test user.
  user.v1.User moderator = 2;
  // An admin test user.
  user.v1.User admin = 3;
}

// A descriptor for a service.
message ServiceDescriptor {
  // The name of the service.
  string name = 1;
  // The names of the methods.
  repeated string methods = 2;
}
