syntax = "proto3";

package user.v1;

import "chat/v1/chat.proto";
import "common/v1/common.proto";
import "google/protobuf/timestamp.proto";
import "resource/v1/resource.proto";

// Service for managing users.
service UserService {
  // Checks if a user exists by ID.
  rpc Exists(ExistsRequest) returns (ExistsResponse);

  // Authenticates a user.
  rpc Auth(AuthRequest) returns (AuthResponse);

  // Verifies an email.
  rpc VerifyEmail(VerifyEmailRequest) returns (VerifyEmailResponse);

  // Creates a new user.
  rpc Create(CreateRequest) returns (CreateResponse);

  // Deletes a user by ID.
  //
  // Requires Authentication: Only the user itself can delete his own account.
  rpc Delete(DeleteRequest) returns (DeleteResponse);

  // Updates a user.
  //
  // Requires Authentication: Only the user itself can update his own account.
  rpc Update(UpdateRequest) returns (UpdateResponse);

  // Get multiple users by ID.
  //
  // Requires Authentication: All authenticated users can get multiple users.
  rpc Get(GetRequest) returns (GetResponse);

  // Searches for users by query.
  //
  // Requires Authentication: All authenticated users can search for users.
  rpc Search(SearchRequest) returns (SearchResponse);

  // Blocks a user.
  //
  // Requires Authentication: Only the user itself can block or unblock.
  rpc Block(BlockRequest) returns (BlockResponse);

  // Check if a user is blocked.
  //
  // Requires Authentication: Only authenticated users can do this.
  rpc IsBlocked(IsBlockedRequest) returns (IsBlockedResponse);

  // Follows a user.
  //
  // Requires Authentication: Only authenticated users can do this.
  rpc Follow(FollowRequest) returns (FollowResponse);
}

// Request message for checking if a user exists.
message ExistsRequest {
  // User ID of the user.
  string user_id = 1;
}

// Response message for checking if a user exists.
message ExistsResponse {
  // The error, if any.
  optional common.v1.Error error = 1;
}

// Request message for authenticating a user.
message AuthRequest {
  // User ID of the user. Required if no token is provided.
  optional string user_id = 1;
  // Password of the user. Required if no token is provided.
  optional string password = 2;
}

// Response message for authenticating a user.
message AuthResponse {
  // Authentication token.
  string token = 1;
  // The user.
  User user = 2;
  // The error, if any.
  optional common.v1.Error error = 3;
}

// Request message for verifying an email.
message VerifyEmailRequest {
  // The E-Mail to verify
  string email = 1;
}

// Response message for verifying an email.
message VerifyEmailResponse {
  // The error, if any.
  optional common.v1.Error error = 1;
}

// Request message for creating a user.
message CreateRequest {
  // Unique user identifier.
  string user_id = 1;
  // Username of the user.
  string username = 2;
  // Email of the user.
  string email = 3;
  // Password of the user.
  string password = 4;
  // E-Mail verification token.
  string verification_token = 5;
}

// Response message for creating a user.
message CreateResponse {
  // The error, if any.
  optional common.v1.Error error = 1;
}

// Request message for deleting a user.
message DeleteRequest {
  // Password of the user.
  string password = 1;
}

// Response message for deleting a user.
message DeleteResponse {
  // The error, if any.
  optional common.v1.Error error = 1;
}

// Request message for updating a user.
message UpdateRequest {
  // Username of the user.
  optional string username = 2;
  // Email of the user.
  optional string email = 3;
  // Password of the user.
  optional string password = 4;
}

// Response message for updating a user.
message UpdateResponse {
  // The error, if any.
  optional common.v1.Error error = 1;
}

// Request message for getting users.
message GetRequest {
  // IDs of the users to get.
  repeated string user_id = 1;
}

// Response message for getting users.
message GetResponse {
  // The returned user profiles.
  repeated UserProfile users = 1;
  // The error, if any.
  common.v1.Error error = 2;
}

// Request message for searching users.
message SearchRequest {
  // Query string to search for.
  string query = 1;
  // The maximum number of users to load.
  uint32 limit = 2;
}

// Response message for searching users.
message SearchResponse {
  // List of users matching the query.
  repeated UserProfile users = 1;
  // The error, if any.
  optional common.v1.Error error = 2;
}

// Request message for blocking a user.
message BlockRequest {
  // ID of the user to block.
  string user_id = 1;
  // Whether to block or unblock the user.
  bool block = 2;
}

// Response message for blocking a user.
message BlockResponse {
  // The error, if any.
  optional common.v1.Error error = 1;
}

// Request for checking the blocking status of a user.
message IsBlockedRequest {
  // ID of the user to check.
  string user_id = 1;
}

// Response for checking the blocking status of a user.
message IsBlockedResponse {
  oneof result {
    // If the user is blocked.
    bool blocked = 1;
    // The error, if any.
    common.v1.Error error = 2;
  }
}

// Request for following a user.
message FollowRequest {
  // ID of the user to follow.
  string user_id = 1;
  // Whether to unfollow the user.
  bool unfollow = 2;
}

// Response for following a user.
message FollowResponse {
  // The error, if any.
  optional common.v1.Error error = 1;
}

// An application user.
//
// When used in an RPC response, the password **must** be empty.
message User {
  // Unique user identifier.
  string user_id = 1;
  // Username of the user.
  string username = 2;
  // Email of the user.
  string email = 3;
  // Password of the user.
  //
  // When used in an RPC response, the password **must** be empty.
  string password = 4;
  // Role of the user.
  UserRole role = 5;
  // Timestamp when the user was created.
  google.protobuf.Timestamp created_at = 6;
  // Icon/Avatar of the user.
  resource.v1.ResourceId icon = 7;
  // Notifications of the user.
  repeated Notification notifications = 8;
  // Channels the User is in
  repeated chat.v1.Channel channels = 9;
  // The followers of the user.
  repeated string followers = 10;
  // The users the user is following.
  repeated string following = 11;
}

// User profile.
//
// A safe representation of a user without sensitive information.
message UserProfile {
  // Unique user identifier.
  string user_id = 1;
  // Username of the user.
  string username = 2;
  // Role of the user.
  UserRole role = 3;
  // Timestamp when the user was created.
  google.protobuf.Timestamp created_at = 4;
  // Icon/Avatar of the user.
  resource.v1.ResourceId icon = 5;
  // The number of followers the user has.
  uint32 followers = 6;
  // The number of users the user is following.
  uint32 following = 7;
}

// Role of the user.
enum UserRole {
  // Default value is a normal user.
  USER_ROLE_USER_UNSPECIFIED = 0;
  // A moderator user.
  USER_ROLE_MODERATOR = 1;
  // An administrator user.
  USER_ROLE_ADMIN = 2;
}

// A user notification.
message Notification {
  // ID of the notification.
  string notification_id = 1;
  // Timestamp of the notification.
  google.protobuf.Timestamp timestamp = 2;
  // The type of the notification.
  oneof notification {
    // The user got invited to a user chat.
    InviteNotification invite = 3;
    // The user received a message.
    MessageNotification message = 4;
  }
}

// A chat notification.
message InviteNotification {
  // ID of the chat channel.
  string channel_id = 1;
  // ID of the user who invited the user.
  string invited_by = 2;
  // Whether the user was uninvited.
  bool uninvited = 3;
}

// A chat message notification.
message MessageNotification {
  // ID of the chat channel.
  string channel_id = 1;
  // ID of the user who sent the message.
  string sender_id = 2;
  // The message.
  chat.v1.Message message = 3;
}
